[project]
name = "bookmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.18",
    "bs4>=0.0.2",
    "django>=5.2",
    "openai>=1.75.0",
    "requests>=2.32.3",
]
